import '../../styles/globals.css';
import '../../styles/button.css';

import Header from '../../layouts/Header/Header';
import Footer from '../../layouts/Footer/Footer';

import '../i18n';
import { dir } from 'i18next';

export const metadata = {
  title: "Mill.az | Home",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
  },
};

export async function generateStaticParams() {
  return ['az', 'en', 'ru'].map((locale) => ({ locale }));
}

export default async function LocaleLayout({ children, params }) {
  const locale = params.locale;
  const direction = dir(locale);

  return (
    <html lang={locale} dir={direction}>
      <body>
        <div className="page">
          <Header />
          <main className="main">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
